# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowsum_Mat <- function(M) {
    .Call('_clustERGM_rowsum_Mat', PACKAGE = 'clustERGM', M)
}

colsum_Mat <- function(M) {
    .Call('_clustERGM_colsum_Mat', PACKAGE = 'clustERGM', M)
}

epan <- function(input) {
    .Call('_clustERGM_epan', PACKAGE = 'clustERGM', input)
}

gamma_update_HMM_stat_dir <- function(gamma, pi, theta, network, N, K) {
    .Call('_clustERGM_gamma_update_HMM_stat_dir', PACKAGE = 'clustERGM', gamma, pi, theta, network, N, K)
}

grad_HMM_stat_dir_oe <- function(theta, gamma, network, N, K) {
    .Call('_clustERGM_grad_HMM_stat_dir_oe', PACKAGE = 'clustERGM', theta, gamma, network, N, K)
}

grad_HMM_stat_dir_re <- function(theta, gamma, network, N, K) {
    .Call('_clustERGM_grad_HMM_stat_dir_re', PACKAGE = 'clustERGM', theta, gamma, network, N, K)
}

hess_HMM_stat_dir_oe <- function(theta, gamma, N, K) {
    .Call('_clustERGM_hess_HMM_stat_dir_oe', PACKAGE = 'clustERGM', theta, gamma, N, K)
}

hess_HMM_stat_dir_re <- function(theta, gamma, N, K) {
    .Call('_clustERGM_hess_HMM_stat_dir_re', PACKAGE = 'clustERGM', theta, gamma, N, K)
}

hess_HMM_stat_dir_oe_re <- function(theta, gamma, N, K) {
    .Call('_clustERGM_hess_HMM_stat_dir_oe_re', PACKAGE = 'clustERGM', theta, gamma, N, K)
}

ELBO_conv_HMM_stat_dir <- function(gamma, alpha, theta, network, N, K) {
    .Call('_clustERGM_ELBO_conv_HMM_stat_dir', PACKAGE = 'clustERGM', gamma, alpha, theta, network, N, K)
}

grad_HMM_stat_dir_oe_K1 <- function(theta, network, N) {
    .Call('_clustERGM_grad_HMM_stat_dir_oe_K1', PACKAGE = 'clustERGM', theta, network, N)
}

grad_HMM_stat_dir_re_K1 <- function(theta, network, N) {
    .Call('_clustERGM_grad_HMM_stat_dir_re_K1', PACKAGE = 'clustERGM', theta, network, N)
}

hess_HMM_stat_dir_oe_K1 <- function(theta, N) {
    .Call('_clustERGM_hess_HMM_stat_dir_oe_K1', PACKAGE = 'clustERGM', theta, N)
}

hess_HMM_stat_dir_re_K1 <- function(theta, N) {
    .Call('_clustERGM_hess_HMM_stat_dir_re_K1', PACKAGE = 'clustERGM', theta, N)
}

hess_HMM_stat_dir_oe_re_K1 <- function(theta, N) {
    .Call('_clustERGM_hess_HMM_stat_dir_oe_re_K1', PACKAGE = 'clustERGM', theta, N)
}

ELBO_conv_HMM_stat_dir_K1 <- function(theta, network, N) {
    .Call('_clustERGM_ELBO_conv_HMM_stat_dir_K1', PACKAGE = 'clustERGM', theta, network, N)
}

